### ISSUE TITLE
Bug with pantry calendar on mobile

### ISSUE THREAD

**Issue by whatthestone** [whatthestone/milliondollarquestion#34]
https://www.npmjs.com/package/react-mobile-datepicker

can try using this for mobile 

![IMG_3123](https://user-images.githubusercontent.com/15033145/82162537-1e3cc880-985a-11ea-9858-da958ab28562.jpg)

Cannot pick from calendar due to scrolling issues on modal

**Comment by StreetLamb** [comment]
Fixed with commit f65c760
