### ISSUE TITLE
Pantry items have 2 actions - EDIT and COOK

### ISSUE THREAD

**Issue by whatthestone** [whatthestone/milliondollarquestion#35]
1. edit brings you to the same modal we have right now
2. cook brings you to qn page to query a recipe. Header of qn page says "Find recipes with CHICKEN" 
  - fetches recipe with chicken and the input queries

**Comment by StreetLamb** [comment]
Fixed with commit ddb697a702d412ee1303b778a41d9dc9be8e7300
